// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FindDuplicates(arg1:Array<main.FileInfo>):Promise<Array<main.DuplicateGroup>>;

export function ScanDirectory(arg1:string):Promise<Array<main.FileInfo>>;
