// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConversionJob(arg1) {
  return window['go']['main']['App']['CancelConversionJob'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ClearConversionHistory() {
  return window['go']['main']['App']['ClearConversionHistory']();
}

export function CopyResourceNameToClipboard(arg1) {
  return window['go']['main']['App']['CopyResourceNameToClipboard'](arg1);
}

export function DeleteConversionJob(arg1) {
  return window['go']['main']['App']['DeleteConversionJob'](arg1);
}

export function DownloadAllJobResults(arg1, arg2) {
  return window['go']['main']['App']['DownloadAllJobResults'](arg1, arg2);
}

export function DownloadConversionResult(arg1, arg2) {
  return window['go']['main']['App']['DownloadConversionResult'](arg1, arg2);
}

export function FindDuplicates(arg1) {
  return window['go']['main']['App']['FindDuplicates'](arg1);
}

export function GetAllConversionJobs() {
  return window['go']['main']['App']['GetAllConversionJobs']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetFiveMResourcesPath() {
  return window['go']['main']['App']['GetFiveMResourcesPath']();
}

export function GetJobResults(arg1) {
  return window['go']['main']['App']['GetJobResults'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MergeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeFiles'](arg1, arg2, arg3);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RetryConversionJob(arg1) {
  return window['go']['main']['App']['RetryConversionJob'](arg1);
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectDownloadFolder() {
  return window['go']['main']['App']['SelectDownloadFolder']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetFiveMResourcesPath(arg1) {
  return window['go']['main']['App']['SetFiveMResourcesPath'](arg1);
}

export function SetHardwareAcceleration(arg1) {
  return window['go']['main']['App']['SetHardwareAcceleration'](arg1);
}

export function SetLaunchOnStartup(arg1) {
  return window['go']['main']['App']['SetLaunchOnStartup'](arg1);
}

export function StartMerge(arg1, arg2) {
  return window['go']['main']['App']['StartMerge'](arg1, arg2);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function SubmitConversion(arg1) {
  return window['go']['main']['App']['SubmitConversion'](arg1);
}

export function UpdateDiscordPresence(arg1) {
  return window['go']['main']['App']['UpdateDiscordPresence'](arg1);
}

export function ValidateMerge(arg1, arg2) {
  return window['go']['main']['App']['ValidateMerge'](arg1, arg2);
}
