// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function FindDuplicates(arg1) {
  return window['go']['main']['App']['FindDuplicates'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function UpdateDiscordPresence(arg1) {
  return window['go']['main']['App']['UpdateDiscordPresence'](arg1);
}
