// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScan():Promise<void>;

export function FindDuplicates(arg1:Array<main.FileInfo>):Promise<Array<main.DuplicateGroup>>;

export function ScanDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function SelectFolder():Promise<string>;

export function StartScan(arg1:string):Promise<void>;

export function UpdateDiscordPresence(arg1:string):Promise<void>;
